#pragma once

enum {
    DEVICE_WEBSOCKET_URI_MAX = 512,
    DEVICE_WEBSOCKET_TOKEN_MAX = 1024,
    DEVICE_WEBSOCKET_IDENTIFIER_MAX = 64,
    DEVICE_WEBSOCKET_CONTROL_MAX = 4096,
    DEVICE_WEBSOCKET_BINARY_MAX = 4112,
    DEVICE_WEBSOCKET_TX_QUEUE_DEPTH = 4,
};
