import importlib.util
import json
import pathlib
import tempfile
import unittest


PROJECT = pathlib.Path(__file__).resolve().parents[2]
MODULE_PATH = PROJECT / "tools" / "firmware_sbom.py"
SPEC = importlib.util.spec_from_file_location("firmware_sbom", MODULE_PATH)
SBOM = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader
SPEC.loader.exec_module(SBOM)
POLICY_PATH = PROJECT / "firmware" / "sbom-release-policy.json"


class FirmwareSBOMPolicyTests(unittest.TestCase):
    def test_release_policy_freezes_tool_build_and_upstreams(self):
        policy, _ = SBOM.load_policy(POLICY_PATH)
        self.assertEqual(policy["sbom_tool"]["version"], "1.2.0")
        self.assertEqual(policy["sbom_tool"]["spdx_version"], "SPDX-2.2")
        self.assertEqual(policy["project"]["esp_idf_version"], "6.0.2")
        self.assertEqual(
            policy["project"]["xiaozhi_commit"],
            "18a60b8051f5ee6a25beed6248ed84c7fcc742bf",
        )
        self.assertEqual(
            policy["project"]["esp_claw_commit"],
            "9ba07d013329df480e34a1a59d1513ab783d8a52",
        )
        self.assertEqual(policy["schema_version"], 2)
        self.assertEqual(len(policy["artifacts"]), 12)

    def test_product_esp_claw_patch_is_frozen_and_delivered(self):
        policy, _ = SBOM.load_policy(POLICY_PATH)
        self.assertEqual(
            policy["source_patches"],
            [
                {
                    "root": "project",
                    "source": "patches/esp-claw/0001-redact-agent-content-logs.patch",
                    "bundle": "sources/esp-claw/0001-redact-agent-content-logs.patch",
                    "sha256": "8c239b7eb5a1875ffb211cb65bef96ffa988561b2e373e594626a6011a344316",
                }
            ],
        )

    def test_direct_prebuilt_audio_blind_spots_are_supplemented(self):
        policy, _ = SBOM.load_policy(POLICY_PATH)
        supplemental = {
            item["name"]: item for item in policy["supplemental_prebuilt_packages"]
        }
        self.assertEqual(
            set(supplemental),
            {"espressif/esp_audio_codec", "espressif/esp_audio_effects"},
        )
        for item in supplemental.values():
            self.assertIn("omitted by esp-idf-sbom --rem-unused", item["reason"])
            self.assertEqual(item["license"], "LicenseRef-Espressif-Modified-MIT")

    def test_license_bundle_has_toolchain_and_restricted_component_notices(self):
        policy, _ = SBOM.load_policy(POLICY_PATH)
        self.assertEqual(len(policy["license_files"]), 27)
        bundles = {item["bundle"] for item in policy["license_files"]}
        for required in (
            "licenses/xiaozhi-esp32-MIT.txt",
            "licenses/esp-claw-Apache-2.0.txt",
            "licenses/esp-audio-codec-Modified-MIT.txt",
            "licenses/esp-audio-effects-Modified-MIT.txt",
            "licenses/gcc-runtime-exception.txt",
            "licenses/gcc-GPL-3.0.txt",
            "licenses/toolchain-picolibc.txt",
            "licenses/toolchain-picolibc-GPL-2.0.txt",
        ):
            self.assertIn(required, bundles)

    def test_policy_preserves_honest_release_boundaries(self):
        policy, _ = SBOM.load_policy(POLICY_PATH)
        gates = "\n".join(policy["unresolved_release_gates"])
        self.assertIn("NOASSERTION", gates)
        self.assertIn("not a current CVE", gates)
        self.assertIn("wake-word data", gates)

    def test_canonicalization_removes_random_namespace_and_time(self):
        raw = b"""# Generated by esp-idf-sbom 1.2.0 with random paths

SPDXVersion: SPDX-2.2
DocumentNamespace: http://spdx.org/spdxdocs/random
Created: 2030-01-01T00:00:00Z
"""
        digest = "ab" * 32
        first = SBOM.canonicalize_spdx(raw, "app", digest, 1786233600)
        second = SBOM.canonicalize_spdx(raw, "app", digest, 1786233600)
        self.assertEqual(first, second)
        text = first.decode()
        self.assertIn("Created: 2026-08-09T00:00:00Z", text)
        self.assertIn(f"/app/sha256-{digest}", text)
        self.assertNotIn("random paths", text)

    def test_canonicalization_rejects_ambiguous_metadata(self):
        raw = b"""# Generated by esp-idf-sbom 1.2.0
DocumentNamespace: one
DocumentNamespace: two
Created: 2026-01-01T00:00:00Z
"""
        with self.assertRaisesRegex(SBOM.FirmwareSBOMError, "ambiguous"):
            SBOM.canonicalize_spdx(raw, "app", "ab" * 32, 1786233600)

    def test_path_traversal_and_duplicate_json_are_rejected(self):
        for value in ("../secret", "/absolute", "a\\b", "a/./b"):
            with self.assertRaises(SBOM.FirmwareSBOMError):
                SBOM.safe_relative(value, "test path")
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "duplicate.json"
            path.write_text('{"version":1,"version":1}\n')
            with self.assertRaisesRegex(SBOM.FirmwareSBOMError, "duplicate"):
                SBOM.load_json(path)

    def test_relative_map_archives_require_matching_spdx_components(self):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            mapping = root / "app.map"
            mapping.write_text("esp-idf/example_component/libexample.a(one.c.obj)\n")
            roots = {
                "project": root,
                "idf": root / "idf",
                "toolchain": root / "toolchain",
            }
            policy = {"supplemental_prebuilt_packages": []}
            expected = "SPDXRef-COMPONENT-example-component"
            result = SBOM.inspect_map(mapping, roots, [expected], policy, "bootloader")
            self.assertEqual(result["component_spdx_ids"], [expected])
            with self.assertRaisesRegex(SBOM.FirmwareSBOMError, "absent from SPDX"):
                SBOM.inspect_map(mapping, roots, [], policy, "bootloader")

    def test_unknown_relative_map_archive_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            mapping = root / "app.map"
            mapping.write_text("vendor/libunknown.a(one.c.obj)\n")
            roots = {"project": root, "idf": root / "idf", "toolchain": root / "toolchain"}
            with self.assertRaisesRegex(SBOM.FirmwareSBOMError, "unexpected relative"):
                SBOM.inspect_map(
                    mapping,
                    roots,
                    [],
                    {"supplemental_prebuilt_packages": []},
                    "app",
                )

    def test_ready_marker_binds_canonical_receipt(self):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            receipt = SBOM.canonical_json({"schema_version": 1})
            (root / "READY").write_text(
                f"sha256:{SBOM.sha256_bytes(receipt)}\n"
            )
            SBOM.verify_ready(root, receipt)
            (root / "READY").write_text("sha256:" + "00" * 32 + "\n")
            with self.assertRaisesRegex(SBOM.FirmwareSBOMError, "does not bind"):
                SBOM.verify_ready(root, receipt)

    def test_builder_never_enables_file_tag_license_guessing(self):
        policy, _ = SBOM.load_policy(POLICY_PATH)
        arguments = policy["sbom_tool"]["arguments"]
        self.assertIn("--rem-unused", arguments)
        self.assertIn("--rem-config", arguments)
        self.assertNotIn("--file-tags", arguments)
        source = (PROJECT / "tools" / "build_firmware_sbom_bundle.py").read_text()
        self.assertLess(source.index("firmware-sbom-receipt.json"), source.index('output / "READY"'))


if __name__ == "__main__":
    unittest.main()
